### ISSUE TITLE
XMPP Client stops working after an error

### ISSUE THREAD

**Issue by kry0sc0pic** [ev3nvy/valorant-xmpp-client#1]
Even when I use the callback for the error event, I don't receive anymore `presence` event updates after the error.

This is the error
```
TypeError: Cannot read properties of undefined (reading 'split')
    at parseJid (D:\client_projects\valorant-xmpp-client\built\helpers\parsers.js:6:46)
    at formatRosterInfo (D:\client_projects\valorant-xmpp-client\built\client\friends\friends.js:7:43)
    at D:\client_projects\valorant-xmpp-client\built\client\friends\friends.js:18:29
    at Array.map (<anonymous>)
    at parseRosterInfo (D:\client_projects\valorant-xmpp-client\built\client\friends\friends.js:18:15)
    at formatRoster (D:\client_projects\valorant-xmpp-client\built\client\friends\friends.js:28:60)
    at ValorantXmppClient._mainLoop (D:\client_projects\valorant-xmpp-client\built\client\valorant-xmpp.js:86:71)     
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on ValorantXmppClient instance at:
    at ValorantXmppClient._mainLoop (D:\client_projects\valorant-xmpp-client\built\client\valorant-xmpp.js:112:18)    
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ev3nvy** [comment]
I am aware of the issue, and I have already fixed it, currently running an instance to see if it crashes at any point (has already been 17 hours with no crashes). Expect a release when I reach 24 hours.

**Comment by ev3nvy** [comment]
update to 1.0.0-test.3, reopen if the same crash happens on 1.0.0-test.3
